In [24]:
import pandas as pd
import numpy as np
import re

In [6]:
df=pd.read_csv("airbnb_listings_2br (1).csv")
df.head()

,City,Property Name,Price,Rating,Number of Reviews,Superhost Status,Guest Favorite Status,Property URL
0,Amsterdam,Quiet apartment near the Zoo,"$1,381",4.86,138,True,False,https://www.airbnb.com/rooms/861561560263702727
1,Amsterdam,Luxury canal house Amsterdam,"$2,028",4.86,72,False,False,https://www.airbnb.com/rooms/1415243157452093261
2,Amsterdam,New! City Centre Suites By: B&B61,"$1,272",4.97,243,True,True,https://www.airbnb.com/rooms/669234388249202231
3,Amsterdam,Luxury Amsterdam Houseboat Listing,"$1,118",4.85,107,True,False,https://www.airbnb.com/rooms/1241981153544142223
4,Amsterdam,Apartment in former Bathhouse. Two bedroom ens...,$842,4.88,186,True,True,https://www.airbnb.com/rooms/53248489

In [7]:
df.columns

Index(['City', 'Property Name', 'Price', 'Rating', 'Number of Reviews',
       'Superhost Status', 'Guest Favorite Status', 'Property URL'],
      dtype='object')

In [8]:
df.shape

(468, 8)

In [9]:
df.dtypes

City                      object
Property Name             object
Price                     object
Rating                   float64
Number of Reviews          int64
Superhost Status            bool
Guest Favorite Status       bool
Property URL              object
dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 468 entries, 0 to 467
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   City                   468 non-null    object
 1   Property Name          468 non-null    object
 2   Price                  426 non-null    object
 3   Rating                 451 non-null    float64
 4   Number of Reviews      468 non-null    int64
 5   Superhost Status       468 non-null    bool
 6   Guest Favorite Status  468 non-null    bool
 7   Property URL           468 non-null    object
dtypes: bool(2), float64(1), int64(1), object(4)
memory usage: 23.0+ KB

In [15]:
df.describe(include="all")

,City,Property Name,Price,Rating,Number of Reviews,Superhost Status,Guest Favorite Status,Property URL
count,468,468,426,451.000000,468.000000,468,468,468
unique,10,468,360,NaN,NaN,2,2,468
top,Athens,Large luxury flat with a designer kitchen (2BR...,€20,NaN,NaN,True,True,https://www.airbnb.com/rooms/15955515
freq,50,1,6,NaN,NaN,357,328,1
mean,NaN,NaN,NaN,4.909290,254.096154,NaN,NaN,NaN
std,NaN,NaN,NaN,0.108111,1537.514410,NaN,NaN,NaN
min,NaN,NaN,NaN,4.360000,1.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,4.875000,34.750000,NaN,NaN,NaN
50%,NaN,NaN,NaN,4.940000,101.000000,NaN,NaN,NaN
75%,NaN,NaN,NaN,4.990000,254.750000,NaN,NaN,NaN
max,NaN,NaN,NaN,5.000000,33007.000000,NaN,NaN,NaN

In [11]:
df.isna().sum().sort_values(ascending=False)

Price                    42
Rating                   17
Property Name             0
City                      0
Number of Reviews         0
Superhost Status          0
Guest Favorite Status     0
Property URL              0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df['City'].value_counts()

City
Athens       50
Barcelona    50
London       50
Berlin       50
Budapest     50
Lisbon       50
Rome         50
Paris        50
Vienna       50
Amsterdam    18
Name: count, dtype: int64

In [17]:
df = df.rename(columns={
    "City": "city",
    "Property Name": "property_name",
    "Price": "price_raw",
    "Rating": "rating",
    "Number of Reviews": "number_of_reviews",
    "Superhost Status": "superhost",
    "Guest Favorite Status": "guest_favorite",
    "Property URL": "property_url"
})
df

,city,property_name,price_raw,rating,number_of_reviews,superhost,guest_favorite,property_url
0,Amsterdam,Quiet apartment near the Zoo,"$1,381",4.86,138,True,False,https://www.airbnb.com/rooms/861561560263702727
1,Amsterdam,Luxury canal house Amsterdam,"$2,028",4.86,72,False,False,https://www.airbnb.com/rooms/1415243157452093261
2,Amsterdam,New! City Centre Suites By: B&B61,"$1,272",4.97,243,True,True,https://www.airbnb.com/rooms/669234388249202231
3,Amsterdam,Luxury Amsterdam Houseboat Listing,"$1,118",4.85,107,True,False,https://www.airbnb.com/rooms/1241981153544142223
4,Amsterdam,Apartment in former Bathhouse. Two bedroom ens...,$842,4.88,186,True,True,https://www.airbnb.com/rooms/53248489
...,...,...,...,...,...,...,...,...
463,Vienna,Penthouse with a terrace near Schönbrunn Palace,$976,4.88,428,True,False,https://www.airbnb.com/rooms/631116125730012562
464,Vienna,Modern Penthouse up to 10 | Near U1 Nestroyplatz,"$2,274",4.40,20,False,False,https://www.airbnb.com/rooms/1700776258171054225
465,Vienna,Luxury Designer Apartment in Central Location,"$1,616",4.81,305,True,False,https://www.airbnb.com/rooms/21678924
466,Vienna,130m2 Luxusapartment in front of Hundertwasser...,"$1,744",4.89,76,True,True,https://www.airbnb.com/rooms/23334650
467,Vienna,Large luxury flat with a designer kitchen (2BR...,"$2,134",4.98,182,True,True,https://www.airbnb.com/rooms/15955515

In [18]:
for col in ["city", "property_name", "property_url"]:
    df[col] = (
        df[col]
        .astype("string")
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
    )

df["city"] = df["city"].str.title()

In [19]:
df[["city", "property_name", "property_url"]]

,city,property_name,property_url
0,Amsterdam,Quiet apartment near the Zoo,https://www.airbnb.com/rooms/861561560263702727
1,Amsterdam,Luxury canal house Amsterdam,https://www.airbnb.com/rooms/1415243157452093261
2,Amsterdam,New! City Centre Suites By: B&B61,https://www.airbnb.com/rooms/669234388249202231
3,Amsterdam,Luxury Amsterdam Houseboat Listing,https://www.airbnb.com/rooms/1241981153544142223
4,Amsterdam,Apartment in former Bathhouse. Two bedroom ens...,https://www.airbnb.com/rooms/53248489
...,...,...,...
463,Vienna,Penthouse with a terrace near Schönbrunn Palace,https://www.airbnb.com/rooms/631116125730012562
464,Vienna,Modern Penthouse up to 10 | Near U1 Nestroyplatz,https://www.airbnb.com/rooms/1700776258171054225
465,Vienna,Luxury Designer Apartment in Central Location,https://www.airbnb.com/rooms/21678924
466,Vienna,130m2 Luxusapartment in front of Hundertwasser...,https://www.airbnb.com/rooms/23334650
467,Vienna,Large luxury flat with a designer kitchen (2BR...,https://www.airbnb.com/rooms/15955515

In [20]:
def to_bool(x):
    if pd.isna(x):
        return pd.NA
    if isinstance(x, bool):
        return x
    s = str(x).strip().lower()
    if s in ["true", "1", "yes"]:
        return True
    if s in ["false", "0", "no"]:
        return False
    return pd.NA

for col in ["superhost", "guest_favorite"]:
    df[col] = df[col].map(to_bool).astype("boolean")

In [25]:

def parse_price(x):
    if pd.isna(x):
        return pd.Series([np.nan, np.nan])

    s = str(x).strip()
    if s == "" or s.lower() == "nan":
        return pd.Series([np.nan, np.nan])

    currency = np.nan
    if "$" in s:
        currency = "USD"
    elif "€" in s or "EUR" in s.upper():
        currency = "EUR"
    elif "£" in s:
        currency = "GBP"

    m = re.search(r"(\d[\d,]*(?:\.\d+)?)", s)
    amount = float(m.group(1).replace(",", "")) if m else np.nan

    return pd.Series([amount, currency])

df[["price_amount", "price_currency"]] = df["price_raw"].apply(parse_price)

df["price_suspicious"] = (
    df["price_amount"].notna() &
    ((df["price_amount"] < 10) | (df["price_amount"] > 10000))
)

In [35]:
df["property_name_key"] = (
    df["property_name"]
    .str.lower()
    .str.replace(r"[^\w\s]", "", regex=True)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [28]:
df["rating"] = pd.to_numeric(df["rating"], errors="coerce")
df.loc[(df["rating"] < 0) | (df["rating"] > 5), "rating"] = np.nan

In [29]:
df["number_of_reviews"] = pd.to_numeric(
    df["number_of_reviews"], errors="coerce"
).astype("Int64")

df.loc[df["number_of_reviews"] < 0, "number_of_reviews"] = pd.NA

df["reviews_outlier_flag"] = df["number_of_reviews"] > 5000

In [31]:
df["listing_id"] = df["property_url"].str.extract(r"/rooms/(\d+)")[0]

In [32]:
print("Exact duplicates:", df.duplicated().sum())
print("Duplicate URLs:", df.duplicated(subset=["property_url"]).sum())

df = df.drop_duplicates()
df = df.drop_duplicates(subset=["property_url"], keep="first")

Exact duplicates: 0
Duplicate URLs: 0

In [36]:
dup_names = df[df.duplicated(subset=["city", "property_name_key"], keep=False)]
print(dup_names[["city", "property_name", "property_url"]])

Empty DataFrame
Columns: [city, property_name, property_url]
Index: []

In [37]:
missing_report = df.isna().sum().sort_values(ascending=False)
print(missing_report)

price_amount            46
price_raw               42
price_currency          42
rating                  17
property_name            0
city                     0
superhost                0
number_of_reviews        0
property_url             0
guest_favorite           0
price_suspicious         0
reviews_outlier_flag     0
listing_id               0
property_name_key        0
dtype: int64

In [38]:
df = df.dropna(subset=["city", "property_url"])

In [41]:
mask = df["price_amount"].isna() & df["price_raw"].notna()
print(df.loc[mask, ["city", "property_name", "price_raw", "price_currency"]])

          city                                   property_name price_raw  \
79   Barcelona  TOP10 street in the world by Time Out Magazine        €,
93   Barcelona            Stylish Apt in the Heart of the City        €,
121     Berlin        2-Bedroom with 90sqm Apartment & Balcony        €,
126     Berlin  2-Bedroom Apartment with 2 Bathrooms & Balcony        €,

    price_currency
79             EUR
93             EUR
121            EUR
126            EUR

In [42]:
df["price_parse_failed"] = df["price_raw"].notna() & df["price_amount"].isna()

print(df["price_parse_failed"].sum(), "rows with unparseable price")

4 rows with unparseable price

In [43]:
print(df.loc[df["price_suspicious"], ["city","property_name","price_raw","price_amount","price_currency"]].to_string())

print(df.loc[df["reviews_outlier_flag"], ["city","property_name","number_of_reviews","rating","property_url"]].to_string())

print("dupURL:", df.duplicated(subset=["property_url"]).sum(),
      "| dupID:", df.duplicated(subset=["listing_id"]).sum(),
      "| dupCityName:", df.duplicated(subset=["city","property_name_key"]).sum(),
      "| dupFullRow:", df.duplicated().sum())

          city                                       property_name price_raw  price_amount price_currency
33      Athens      Acropolis area family friendly 2 bdr apartment      EUR8          8.00            EUR
71   Barcelona       Picasso Terrace Penthouse by Cocoon Barcelona     €6.88          6.88            EUR
83   Barcelona           Superior 3 bedroom apartment with terrace     €6.88          6.88            EUR
97   Barcelona                A designer duplex in the city center     €9.50          9.50            EUR
110  Barcelona        ★ PLAZA CATALUNYA DELUXE by Cocoon Barcelona     €6.88          6.88            EUR
113  Barcelona   3BR Apartment w/ 100m² Private Terrace – Eixample     €9.50          9.50            EUR
127     Berlin                      Attic Loft in Historic Factory       €1,          1.00            EUR
358      Paris       UrbanFlat 111 - Luxurious Apartment Madeleine   EUR1.00          1.00            EUR
373       Rome              * A stone's throw from the Colosseum *     €6.00          6.00            EUR
414       Rome  Vatican Family Step-Free Apt | Metro A · AC · 2.5B     €1.20          1.20            EUR
     city                             property_name  number_of_reviews  rating                                      property_url
415  Rome  iFlat | Retro Apartment near St. Peter's              33007     NaN  https://www.airbnb.com/rooms/1779713475962840561
dupURL: 0 | dupID: 0 | dupCityName: 0 | dupFullRow: 0

In [44]:
df["price_is_per_night"] = (
    df["price_raw"]
    .astype("string")
    .str.contains(r"\bnight\b", case=False, na=False)
    .fillna(False)
    .astype("boolean")
)

df["price_suspicious"] = (
    df["price_suspicious"].fillna(False)
    | df["price_is_per_night"].fillna(False)
).astype("boolean")

print("Suspicious now:", int(df["price_suspicious"].sum()))

Suspicious now: 12

In [45]:
print(df["price_amount"].describe())
print(df["rating"].describe())
print(df["number_of_reviews"].describe())

print(df.loc[df["price_suspicious"], ["city", "property_name", "price_raw", "price_amount"]])
print(df.loc[df["reviews_outlier_flag"], ["city", "property_name", "number_of_reviews"]])

count     422.000000
mean     1075.440142
std       719.474761
min         1.000000
25%       626.750000
50%      1001.000000
75%      1480.750000
max      4015.000000
Name: price_amount, dtype: float64
count    451.000000
mean       4.909290
std        0.108111
min        4.360000
25%        4.875000
50%        4.940000
75%        4.990000
max        5.000000
Name: rating, dtype: float64
count         468.0
mean     254.096154
std      1537.51441
min             1.0
25%           34.75
50%           101.0
75%          254.75
max         33007.0
Name: number_of_reviews, dtype: Float64
          city                                      property_name  price_raw  \
33      Athens     Acropolis area family friendly 2 bdr apartment       EUR8
71   Barcelona      Picasso Terrace Penthouse by Cocoon Barcelona      €6.88
76   Barcelona                           Penthouse with a terrace  €25 night
83   Barcelona          Superior 3 bedroom apartment with terrace      €6.88
97   Barcelona               A designer duplex in the city center      €9.50
110  Barcelona       ★ PLAZA CATALUNYA DELUXE by Cocoon Barcelona      €6.88
113  Barcelona  3BR Apartment w/ 100m² Private Terrace – Eixample      €9.50
127     Berlin                     Attic Loft in Historic Factory        €1,
271     London                             Fabulous Chelsea 2 bed  £25 night
358      Paris      UrbanFlat 111 - Luxurious Apartment Madeleine    EUR1.00
373       Rome             * A stone's throw from the Colosseum *      €6.00
414       Rome  Vatican Family Step-Free Apt | Metro A · AC · ...      €1.20

     price_amount
33           8.00
71           6.88
76          25.00
83           6.88
97           9.50
110          6.88
113          9.50
127          1.00
271         25.00
358          1.00
373          6.00
414          1.20
     city                             property_name  number_of_reviews
415  Rome  iFlat | Retro Apartment near St. Peter's              33007

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 468 entries, 0 to 467
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   city                  468 non-null    string
 1   property_name         468 non-null    string
 2   price_raw             426 non-null    object
 3   rating                451 non-null    float64
 4   number_of_reviews     468 non-null    Int64
 5   superhost             468 non-null    boolean
 6   guest_favorite        468 non-null    boolean
 7   property_url          468 non-null    string
 8   price_amount          422 non-null    float64
 9   price_currency        426 non-null    object
 10  price_suspicious      468 non-null    boolean
 11  reviews_outlier_flag  468 non-null    boolean
 12  listing_id            468 non-null    string
 13  property_name_key     468 non-null    string
 14  price_parse_failed    468 non-null    bool
 15  price_is_per_night    468 non-null    boolean
dtypes: Int64(1), bool(1), boolean(5), float64(2), object(2), string(5)
memory usage: 42.2+ KB

In [47]:
df.isnull().sum()

city                     0
property_name            0
price_raw               42
rating                  17
number_of_reviews        0
superhost                0
guest_favorite           0
property_url             0
price_amount            46
price_currency          42
price_suspicious         0
reviews_outlier_flag     0
listing_id               0
property_name_key        0
price_parse_failed       0
price_is_per_night       0
dtype: int64

In [48]:
df.to_csv("airbnb_cleaned.csv", index=False, encoding="utf-8-sig")